---
title: "a formula interface for corHMM $Q$ matrices"
---

For multi-trait models (where the state vector consists of combinations of categories of different traits) we'd like to be able to use Wilkinson-Rogers-like formulas to specify a mapping from model parameters to the elements of $Q$ matrices. This will have several benefits:

- simplifies specification of $Q$
- allows for additive models (i.e. or more general mappings from sets of parameters to rates)
- makes it easy to compute *contrasts* (differences in rates, or differences in differences in rates in the case of interactions)

In general we want to be able to specify the dependence of rates of change of one trait on the states of other traits. We should also be able to specify symmetry/directionality/asymmetry.

Taking the model from Eckert et al., where we have traits `ag` (accessory glands), `pc` (parental care), `sc` (spawning mode/sperm competition). The main model used in the paper would be specified as

```r
list(ag ~ pc*sc, pc ~ 1, sc ~ 1)
```

to denote that rates of gain/loss in `pc`, `sc` are independent of the other traits, and `ag` gain/loss are different in every (`pc` × `sc`) state. More specifically we could call this

```r
list(ag ~ asymm(pc*sc), pc ~ asymm(1), sc ~ asymm(1))
```
to denote that the rates are asymmetric (different parameters for gain and loss). Other possibilities would be `symm()` (symmetric), `directed()` (transitions only allowed in the direction of an ordered set of states; possibly allow "down" or "up"?). In principle it should also be possible to specify different models in each direction, `~pc*sc` for gains and `~1` for losses; not quite sure how to specify this. Maybe `list(ag = ~symm(pc*sc), pc = list(~1, ~sc), ...)` ? Want a reasonable compromise between consistency and simple defaults. (Use `sym`, `ard` `eq` for consistency with current corHMM "SYM"?

How should all of this extend to covarion models (i.e. specifying what changes between covarion blocks)?

* parse formulas
* set up as many model matrices as necessary (model matrices are small so duplication shouldn't be a problem), e.g. one for gain/loss (not sure what to do about traits with many levels?)
* set up machinery for partitioning a parameter vector, multiplying model frames by the corresponding sub-vector, and inserting the results into the appropriate elements of the $Q$ matrix ...

If we don't need to allow for arbitrary nesting then we probably don't need `reformulas` machinery for recursive processing. Slightly easier to deal  with if make this a *named list* (e.g. `x = ~ form`) rather than an list with unnamed components (`x ~ form`), but the latter seems more natural ?

